name: Advanced Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
      - name: create file list
        id: files_list
        run: |
          pip install pandas
          pip install tabulate
          sudo wget https://github.com/jgm/pandoc/releases/download/1.15.1/pandoc-1.15.1-1-amd64.deb
          sudo dpkg -i pandoc-1.15.1-1-amd64.deb
          find . -type f  -name "*.table" | xargs -I {} python3 convert.py {}
          mkdir -p pdfs  # create output dir
          find . -type f  -name "*.md" | xargs -I {} pandoc {} -o pdfs/{}.pdf
      

    
          
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.16.0

