name: Advanced Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
      - name: create file list
        id: files_list
        run: |
          pip install pandas
          pip install tabulate
          find . -type f  -name "*.table" | xargs -I {} python3 convert.py {}
          mkdir -p pdfs  # create output dir
          echo "files=$(find . -type f  -name "*.md")" >> $GITHUB_OUTPUT
          
      
      - uses: docker://pandoc/latex:2.9
        with:
          run: |
            echo ${{ steps.files_list.outputs.files }}
            xargs -I {} pandoc --pdf-engine=typst -t pdf {} -o {}.pdf
    
          
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.16.0

