name: Advanced Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
      - name: create file list
        id: files_list
        run: |
          pip install pandas
          printf '"%s"\n' *.table | xargs -I {} python3 convert.py {}
          mkdir -p pdfs  # create output dir
          echo "files=$(printf '"%s" ' *.md)" > $GITHUB_OUTPUT

      - uses: docker://pandoc/latex:2.9
        with:
          args: --output=pdfs/result.pdf ${{ steps.files_list.outputs.files }}
          
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.16.0

